"""Initial migration

Revision ID: 1fe992244247
Revises: 
Create Date: 2026-06-09 23:37:10.323442

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1fe992244247'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('api_key_hash', sa.String(), nullable=False),
    sa.Column('credits', sa.Integer(), nullable=False),
    sa.Column('payee_lightning_address', sa.String(), nullable=True),
    sa.Column('created_at', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('api_key_hash')
    )
    op.create_index(op.f('ix_clients_id'), 'clients', ['id'], unique=False)
    op.create_table('ledger',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('delta_credits', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(), nullable=False),
    sa.Column('ref', sa.String(), nullable=True),
    sa.Column('created_at', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_ledger_client_created', 'ledger', ['client_id', 'created_at'], unique=False)
    op.create_index('idx_ledger_client_id', 'ledger', ['client_id', 'id'], unique=False)
    op.create_index(op.f('ix_ledger_id'), 'ledger', ['id'], unique=False)
    op.create_table('topups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('payment_hash', sa.String(), nullable=False),
    sa.Column('invoice', sa.String(), nullable=False),
    sa.Column('sats', sa.Integer(), nullable=False),
    sa.Column('credits', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.Integer(), nullable=False),
    sa.Column('settled_at', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('payment_hash')
    )
    op.create_index('idx_topups_client_created', 'topups', ['client_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_topups_id'), 'topups', ['id'], unique=False)
    op.create_table('verifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('payment_hash', sa.String(), nullable=False),
    sa.Column('resource', sa.String(), nullable=True),
    sa.Column('created_at', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('client_id', 'payment_hash', name='uix_client_payment_hash')
    )
    op.create_index('idx_verifications_client_created', 'verifications', ['client_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_verifications_id'), 'verifications', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_verifications_id'), table_name='verifications')
    op.drop_index('idx_verifications_client_created', table_name='verifications')
    op.drop_table('verifications')
    op.drop_index(op.f('ix_topups_id'), table_name='topups')
    op.drop_index('idx_topups_client_created', table_name='topups')
    op.drop_table('topups')
    op.drop_index(op.f('ix_ledger_id'), table_name='ledger')
    op.drop_index('idx_ledger_client_id', table_name='ledger')
    op.drop_index('idx_ledger_client_created', table_name='ledger')
    op.drop_table('ledger')
    op.drop_index(op.f('ix_clients_id'), table_name='clients')
    op.drop_table('clients')
    # ### end Alembic commands ###
